common/urls.py
from django.urls import path
from . import views

app_name = "common"

urlpatterns = [
    path("", views.HomeTemplateView.as_view(), name="home"),
    path("dashboard/", views.DashboardTemplateView.as_view(), name="dashboard"),
    path("logout/", views.LogoutRedirectView.as_view(), name="logout"),
    path("user/<int:pk>/", views.UserDetailView.as_view(), name="user-detail"),
    path("user/<int:pk>/change/", views.UserUpdateView.as_view(), name="user-update"),
    path("user/<int:pk>/delete/", views.UserDeleteView.as_view(), name="user-delete"),
]

inventory/urls.py
from django.urls import path
from . import views

app_name = "inventory"

urlpatterns = [
    path("location/", views.LocationListView.as_view(), name="location-list"),
    path("location/add/", views.LocationCreateView.as_view(), name="location-create"),
    path(
        "location/<int:pk>/", views.LocationDetailView.as_view(), name="location-detail"
    ),
    path(
        "location/<int:pk>/change/",
        views.LocationUpdateView.as_view(),
        name="location-update",
    ),
    path(
        "location/<int:pk>/delete/",
        views.LocationDeleteView.as_view(),
        name="location-delete",
    ),
    path("object/", views.ObjectFilterView.as_view(), name="object-list"),
    path("object/add/", views.ObjectCreateView.as_view(), name="object-create"),
    path("object/<int:pk>/", views.ObjectDetailView.as_view(), name="object-detail"),
    path(
        "object/<int:pk>/change/",
        views.ObjectUpdateView.as_view(),
        name="object-update",
    ),
    path(
        "object/<int:pk>/delete/",
        views.ObjectDeleteView.as_view(),
        name="object-delete",
    ),
    path("sensor/add/", views.SensorCreateView.as_view(), name="sensor-create"),
    path("sensor/", views.SensorFilterView.as_view(), name="sensor-list"),
    path(
        "sensor/<int:pk>/",
        views.SensorDetailView.as_view(),
        name="sensor-detail",
    ),
    path(
        "sensor/<int:pk>/change/",
        views.SensorUpdateView.as_view(),
        name="sensor-update",
    ),
    path(
        "sensor/<int:pk>/webhook/",
        views.SensorWebhookView.as_view(),
        name="sensor-webhook",
    ),
    path(
        "sensor/<int:pk>/delete/",
        views.SensorDeleteView.as_view(),
        name="sensor-delete",
    ),
]

maintenance/urls.py
from django.urls import path
from . import views

app_name = "maintenance"

urlpatterns = [
    path("task/", views.TaskFilterView.as_view(), name="task-list"),
    path(
        "task/add/",
        views.TaskCreateView.as_view(),
        name="task-create",
    ),
    path(
        "task/<int:pk>/",
        views.TaskDetailView.as_view(),
        name="task-detail",
    ),
    path(
        "task/<int:pk>/change/",
        views.TaskUpdateView.as_view(),
        name="task-update",
    ),
    path(
        "task/<int:pk>/delete/",
        views.TaskDeleteView.as_view(),
        name="task-delete",
    ),
    path("journal/", views.JournalFilterView.as_view(), name="journal-list"),
    path(
        "journal/add",
        views.JournalCreate.as_view(),
        name="journal-create",
    ),
    path(
        "journal/<int:pk>/",
        views.JournalDetailView.as_view(),
        name="journal-detail",
    ),
    path(
        "journal/<int:pk>/change/",
        views.JournalUpdateView.as_view(),
        name="journal-update",
    ),
    path(
        "journal/<int:pk>/delete/",
        views.JournalDeleteView.as_view(),
        name="journal-delete",
    ),
    path(
        "trigger/add",
        views.TriggerCreateView.as_view(),
        name="trigger-create",
    ),
    path(
        "trigger/<int:pk>/",
        views.TriggerDetailView.as_view(),
        name="trigger-detail",
    ),
    path(
        "trigger/<int:pk>/change/",
        views.TriggerUpdateView.as_view(),
        name="trigger-update",
    ),
    path(
        "trigger/<int:pk>/delete/",
        views.TriggerDeleteView.as_view(),
        name="trigger-delete",
    ),
    path(
        "document/add",
        views.DocumentCreateView.as_view(),
        name="document-create",
    ),
    path(
        "document/<int:pk>/",
        views.DocumentDetailView.as_view(),
        name="document-detail",
    ),
    path(
        "document/<int:pk>/change/",
        views.DocumentUpdateView.as_view(),
        name="document-update",
    ),
    path(
        "document/<int:pk>/delete/",
        views.DocumentDeleteView.as_view(),
        name="document-delete",
    ),
]

objector/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from django.utils.translation import gettext_lazy as _

admin.site.site_header = _("Objector admin")

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("social_django.urls")),
    path("", include("common.urls")),
    path("", include("inventory.urls")),
    path("", include("maintenance.urls")),
]

# add this lines
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

common/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils.translation import gettext_lazy as _
from rules.contrib.models import RulesModelMixin


class User(RulesModelMixin, AbstractUser):
    class Languages(models.TextChoices):
        GERMAN = "de", _("German")
        ENGLISH = "en", _("English")

    send_status_report_at = models.TimeField(
        _("Send status report at"), blank=True, null=True
    )
    status_report_last_sent_at = models.DateTimeField(
        _("Status report last sent at"), blank=True, null=True
    )
    status_report_language = models.CharField(
        _("Status report language"),
        choices=Languages.choices,
        default=Languages.ENGLISH,
        max_length=2,
    )

    def get_picture(self) -> str:
        social_user = self.social_auth.get()
        picture = social_user.extra_data.get("picture", "")
        return picture

    def get_absolute_url(self) -> str:
        return f"/user/{self.id}"

common/forms.py
from django import forms
from .models import User
from django.utils.translation import gettext_lazy as _


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = [
            "first_name",
            "last_name",
            "send_status_report_at",
            "status_report_language",
        ]

    send_status_report_at = forms.TimeField(
        label=_("Send status report at"),
        required=False,
        input_formats=["%H:%M"],
        widget=forms.TimeInput(
            attrs={
                "type": "time",
                "placeholder": "Select a time",
            },
            format="%H:%M",
        ),
    )

common/views.py
from django.contrib.auth import logout as django_logout
from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import (
    RedirectView,
    UpdateView,
    DetailView,
    DeleteView,
    TemplateView,
)
from django.db.models import Min, Max
from inventory.models import Location
from maintenance.models import Task
from inventory.models import Sensor
from django.utils import timezone
from rules.contrib.views import AutoPermissionRequiredMixin
from .models import User
from .forms import UserForm
from django.urls import reverse_lazy


class HomeTemplateView(TemplateView):
    template_name = "common/home.html"


class LogoutRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self, **kwargs) -> str:
        django_logout(self.request)
        domain = settings.SOCIAL_AUTH_AUTH0_DOMAIN
        client_id = settings.SOCIAL_AUTH_AUTH0_KEY
        return_to = self.request.build_absolute_uri("/")
        return f"https://{domain}/v2/logout?client_id={client_id}&returnTo={return_to}"


class DashboardTemplateView(LoginRequiredMixin, TemplateView):
    template_name = "common/dashboard.html"

    def get_context_data(self, *args, **kwargs) -> dict:
        context = super().get_context_data(**kwargs)
        groups = self.request.user.groups.values_list("pk", flat=True)
        groups_as_list = list(groups)
        overdue_tasks_queryset = (
            Task.objects.filter(
                object__owner=self.request.user, status=Task.Statuses.OVERDUE
            )
            | Task.objects.filter(
                object__management_group__in=groups_as_list,
                status=Task.Statuses.OVERDUE,
            )
            | Task.objects.filter(
                object__maintenance_group__in=groups_as_list,
                status=Task.Statuses.OVERDUE,
            )
        )
        due_tasks_queryset = (
            Task.objects.filter(
                object__owner=self.request.user, status=Task.Statuses.DUE
            )
            | Task.objects.filter(
                object__management_group__in=groups_as_list,
                status=Task.Statuses.DUE,
            )
            | Task.objects.filter(
                object__maintenance_group__in=groups_as_list,
                status=Task.Statuses.DUE,
            )
        )
        pending_tasks_queryset = (
            Task.objects.filter(
                object__owner=self.request.user, status=Task.Statuses.PENDING
            )
            | Task.objects.filter(
                object__management_group__in=groups_as_list,
                status=Task.Statuses.PENDING,
            )
            | Task.objects.filter(
                object__maintenance_group__in=groups_as_list,
                status=Task.Statuses.PENDING,
            )
        )
        red_sensors_queryset = (
            Sensor.objects.filter(
                object__owner=self.request.user, status=Sensor.Statuses.RED
            )
            | Sensor.objects.filter(
                object__management_group__in=groups_as_list, status=Sensor.Statuses.RED
            )
            | Sensor.objects.filter(
                object__maintenance_group__in=groups_as_list, status=Sensor.Statuses.RED
            )
        )
        amber_sensors_queryset = (
            Sensor.objects.filter(
                object__owner=self.request.user, status=Sensor.Statuses.AMBER
            )
            | Sensor.objects.filter(
                object__management_group__in=groups_as_list,
                status=Sensor.Statuses.AMBER,
            )
            | Sensor.objects.filter(
                object__maintenance_group__in=groups_as_list,
                status=Sensor.Statuses.AMBER,
            )
        )
        green_sensors_queryset = (
            Sensor.objects.filter(
                object__owner=self.request.user, status=Sensor.Statuses.GREEN
            )
            | Sensor.objects.filter(
                object__management_group__in=groups_as_list,
                status=Sensor.Statuses.GREEN,
            )
            | Sensor.objects.filter(
                object__maintenance_group__in=groups_as_list,
                status=Sensor.Statuses.GREEN,
            )
        )
        location_queryset = (
            Location.objects.filter(
                owner=self.request.user, latitude__isnull=False, longitude__isnull=False
            )
            | Location.objects.filter(
                management_group__in=groups_as_list,
                latitude__isnull=False,
                longitude__isnull=False,
            )
            | Location.objects.filter(
                maintenance_group__in=groups_as_list,
                latitude__isnull=False,
                longitude__isnull=False,
            )
        )
        context["overdue_tasks_count"] = overdue_tasks_queryset.count()
        context["due_tasks_count"] = due_tasks_queryset.count()
        context["pending_tasks_count"] = pending_tasks_queryset.count()
        context["red_sensors_count"] = red_sensors_queryset.count()
        context["amber_sensors_count"] = amber_sensors_queryset.count()
        context["green_sensors_count"] = green_sensors_queryset.count()
        context["locations"] = location_queryset
        context["locations_aggregates"] = location_queryset.aggregate(
            Min("latitude"), Max("latitude"), Min("longitude"), Max("longitude")
        )
        context["current_datetime"] = timezone.now()

        return context


class UserDetailView(AutoPermissionRequiredMixin, DetailView):
    model = User
    raise_exception = True


class UserUpdateView(AutoPermissionRequiredMixin, UpdateView):
    model = User
    raise_exception = True
    form_class = UserForm


class UserDeleteView(AutoPermissionRequiredMixin, DeleteView):
    model = User
    raise_exception = True
    success_url = reverse_lazy("home")

common/templates/common/dashboard.html
{% extends "base.html" %}
{% load i18n %}
{% load l10n %}
{% load static %}
{% block head %}
<meta http-equiv="refresh" content="300">
{# https://www.srihash.org/ #}
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.3/dist/leaflet.css" integrity="sha384-o/2yZuJZWGJ4s/adjxVW71R+EO/LyCwdQfP5UWSgX/w87iiTXuvDZaejd3TsN7mf" crossorigin="anonymous">
<script src="https://unpkg.com/leaflet@1.9.3/dist/leaflet.js" integrity="sha384-okbbMvvx/qfQkmiQKfd5VifbKZ/W8p1qIsWvE1ROPUfHWsDcC8/BnHohF7vPg2T6" crossorigin="anonymous"></script>
{% endblock %}
{% block title %}Objector + {% translate "Dashboard" %}{% endblock %}
{% block h1 %}{% translate "Dashboard" %}{% endblock %}
{% block h2 %}{{ current_datetime }}{% endblock %}
{% block content %}

<div class="px-4 py-5 sm:px-6">
  <h2 id="summary-title" class="text-xl leading-6 font-medium text-gray-900">
    {% translate "Summary" %}
  </h2>
</div>

<div class="grid grid-cols-1 gap-4 sm:grid-cols-2">
  <div class="relative rounded-lg border border-gray-300 bg-white px-6 py-5 shadow-sm flex items-center space-x-3 hover:border-gray-400 focus-within:ring-2 focus-within:ring-offset-2 focus-within:ring-indigo-500">
    <div class="flex-1 min-w-0">
      <p class="text-lg font-medium text-gray-900"><a href="{% url 'maintenance:task-list' %}">{% translate "Tasks" %}</a></p>
      {% if overdue_tasks_count > 0 %}
      <p class="text-base text-red-500 truncate"><a href="{% url 'maintenance:task-list' %}?status=10">{{ overdue_tasks_count }} {% translate "Overdue" %}</a></p>
      {% else %}
      <p class="text-base text-gray-500 truncate"><a href="{% url 'maintenance:task-list' %}">{{ overdue_tasks_count }} {% translate "Overdue" %}</a></p>
      {% endif %}
      {% if due_tasks_count > 0 %}
      <p class="text-base text-amber-500 truncate"><a href="{% url 'maintenance:task-list' %}?status=20">{{ due_tasks_count }} {% translate "Due" %}</a></p>
      {% else %}
      <p class="text-base text-gray-500 truncate"><a href="{% url 'maintenance:task-list' %}">{{ due_tasks_count }} {% translate "Due" %}</a></p>
      {% endif %}
      {% if pending_tasks_count > 0 %}
      <p class="text-base text-green-500 truncate"><a href="{% url 'maintenance:task-list' %}?status=30">{{ pending_tasks_count }} {% translate "Pending" %}</a></p>
      {% else %}
      <p class="text-base text-gray-500 truncate"><a href="{% url 'maintenance:task-list' %}">{{ pending_tasks_count }} {% translate "Pending" %}</a></p>
      {% endif %}
    </div>
  </div>

  <div class="relative rounded-lg border border-gray-300 bg-white px-6 py-5 shadow-sm flex items-center space-x-3 hover:border-gray-400 focus-within:ring-2 focus-within:ring-offset-2 focus-within:ring-indigo-500">
    <div class="flex-1 min-w-0">
      <p class="text-lg font-medium text-gray-900"><a href="{% url 'inventory:sensor-list' %}">{% translate "Sensors" %}</a></p>
      {% if red_sensors_count > 0 %}
      <p class="text-base text-red-500 truncate"><a href="{% url 'inventory:sensor-list' %}?status=10">{{ red_sensors_count }} {% translate "Alert" %}</a></p>
      {% else %}
      <p class="text-base text-gray-500 truncate"><a href="{% url 'inventory:sensor-list' %}">{{ red_sensors_count }} {% translate "Alert" %}</a></p>
      {% endif %}
      {% if amber_sensors_count > 0 %}
      <p class="text-base text-amber-500 truncate"><a href="{% url 'inventory:sensor-list' %}?status=20">{{ amber_sensors_count }} {% translate "Warning" %}</a></p>
      {% else %}
      <p class="text-base text-gray-500 truncate"><a href="{% url 'inventory:sensor-list' %}">{{ amber_sensors_count }} {% translate "Warning" %}</a></p>
      {% endif %}
      {% if green_sensors_count > 0 %}
      <p class="text-base text-green-500 truncate"><a href="{% url 'inventory:sensor-list' %}?status=30">{{ green_sensors_count }} {% translate "Normal" %}</a></p>
      {% else %}
      <p class="text-base text-gray-500 truncate"><a href="{% url 'inventory:sensor-list' %}">{{ green_sensors_count }} {% translate "Normal" %}</a></p>
      {% endif %}
    </div>
  </div>
</div>

{% if locations %}
<div class="px-4 py-5 sm:px-6">
  <h2 id="map-title" class="text-xl leading-6 font-medium text-gray-900">
    {% translate "Map" %}
  </h2>
</div>
<div id="map" style="width: 100%; height: 600px;"></div>
<script>
  var map = L.map('map');
  map.fitBounds([
    [{{ locations_aggregates.latitude__max|default:47.76|unlocalize }}, {{ locations_aggregates.longitude__min|default:6.02|unlocalize }}],
    [{{ locations_aggregates.latitude__min|default:45.77|unlocalize }}, {{ locations_aggregates.longitude__max|default:10.45|unlocalize }}]
  ]);

  L.tileLayer('https://api.mapbox.com/styles/v1/{id}/tiles/{z}/{x}/{y}?access_token={accessToken}', {
    maxZoom: 18,
    attribution: 'Map data &copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors, ' +
      'Imagery © <a href="https://www.mapbox.com/">Mapbox</a>',
    id: 'mapbox/streets-v11',
    tileSize: 512,
    zoomOffset: -1,
    accessToken: 'pk.eyJ1IjoibWFwYm94IiwiYSI6ImNpejY4NXVycTA2emYycXBndHRqcmZ3N3gifQ.rJcFIG214AriISLbB6B5aw'
  }).addTo(map);
  var greenIcon = L.icon({iconUrl: '{% static 'common/img/marker-icon-green.png' %}', iconSize: [25, 41], iconAnchor: [12, 41], popupAnchor: [0, -34]});
  var amberIcon = L.icon({iconUrl: '{% static 'common/img/marker-icon-amber.png' %}', iconSize: [25, 41], iconAnchor: [12, 41], popupAnchor: [0, -34]});
  var redIcon   = L.icon({iconUrl: '{% static 'common/img/marker-icon-red.png' %}',   iconSize: [25, 41], iconAnchor: [12, 41], popupAnchor: [0, -34]});
  {% for location in locations %}
      var marker{{ location.id }} = L.marker([{{ location.latitude|unlocalize }}, {{ location.longitude|unlocalize }}], { icon: {{ location.status_color }}Icon }).bindPopup("<a href='{% url 'inventory:location-detail' location.id %}'>{{ location.name }}</a>").addTo(map);
  {% endfor %}
</script>
{% endif %}
{% endblock %}

common/templates/common/home.html
{% extends 'base.html' %}
{% load i18n %}
{% block title %}Objector + Home{% endblock %}
{% block h1 %}{% translate "Welcome" %}{% endblock %}
{% block h2 %}{% translate "Improve object stamina!" %}{% endblock %}
{% block content %}
<div class="pb-5 border-b border-gray-200">
  <p class="mt-2 max-w-4xl">{% translate "Objector wants to improve your objects stamina - by applying maintenance and keeping track of it." %}</p>
</div>
<div>
  <ol>
    <li>+ {% translate "Add your locations, objects, sensors and maintenance tasks" %}</li>
    <li>+ {% translate "Group objects by location" %}</li>
    <li>+ {% translate "Get to know about upcoming or overdue tasks" %}</li>
    <li>+ {% translate "Set up management and maintenance" %}</li>
    <li>+ {% translate "Receive daily status report" %}</li>
  </ol>
</div>
{% endblock %}

common/templates/common/user_confirm_delete.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}Objector + {% translate "User confirm delete" %} + {{ user }}{% endblock %}
{% block h1 %}{% translate "User confirm delete" %}{% endblock %}
{% block h2 %}{{ user }}{% endblock %}
{% block content %}
<form method="post">{% csrf_token %}
  <p>{% translate "Are you sure you want to delete" %} "{{ user }}"?</p>
  <div class="pt-5">
    <div class="flex justify-end">
      <button type="submit" class="ml-3 bg-white py-2 px-4 border border-red-300 rounded-md shadow-sm text-sm font-medium text-red-700 hover:bg-red-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
        {% translate "Delete" %}
      </button>
      <a href="{% url 'common:user-detail' user.id %}" class="ml-3 bg-white py-2 px-4 border border-gray-300 rounded-md shadow-sm text-sm font-medium text-gray-700 hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
        {% translate "Cancel" %}
      </a>
    </div>
  </div>
</form>
{% endblock %}

common/templates/common/user_detail.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}Objector + {% translate "User detail" %} + {{ user }}{% endblock %}
{% block h1 %}{% translate "User detail" %}{% endblock %}
{% block h2 %}{{ user }}{% endblock %}
{% block content %}
<section aria-labelledby="location-detail-title">
  <div class="bg-white shadow sm:rounded-lg">
    <div class="border-t border-gray-200 px-4 py-5 sm:px-6">
      <dl class="grid grid-cols-1 gap-x-4 gap-y-8 sm:grid-cols-2">
        <div class="sm:col-span-2">
          <dt class="text-sm font-medium text-gray-500">
            {% translate "Username" %}
          </dt>
          <dd class="mt-1 text-sm text-gray-900">
            {{ user.username }}
          </dd>
        </div>
        <div class="sm:col-span-1">
          <dt class="text-sm font-medium text-gray-500">
            {% translate "First name" %}
          </dt>
          <dd class="mt-1 text-sm text-gray-900">
            {{ user.first_name }}
          </dd>
        </div>
        <div class="sm:col-span-1">
          <dt class="text-sm font-medium text-gray-500">
            {% translate "Last name" %}
          </dt>
          <dd class="mt-1 text-sm text-gray-900">
            {{ user.last_name }}
          </dd>
        </div>
      </dl>
    </div>
    <div class="border-t border-gray-200 px-4 py-5 sm:px-6">
      <dl class="grid grid-cols-1 gap-x-4 gap-y-8 sm:grid-cols-2">
        <div class="sm:col-span-1">
          <dt class="text-sm font-medium text-gray-500">
            {% translate "Send status report at" %}
          </dt>
          <dd class="mt-1 text-sm text-gray-900">
            {{ user.send_status_report_at }}
          </dd>
        </div>
        <div class="sm:col-span-1">
          <dt class="text-sm font-medium text-gray-500">
            {% translate "Status report last sent at" %}
          </dt>
          <dd class="mt-1 text-sm text-gray-900">
            {{ user.status_report_last_sent_at }}
          </dd>
        </div>
        <div class="sm:col-span-2">
          <dt class="text-sm font-medium text-gray-500">
            {% translate "Status report language" %}
          </dt>
          <dd class="mt-1 text-sm text-gray-900">
            {{ user.get_status_report_language_display }}
          </dd>
        </div>
      </dl>
    </div>
    <div class="border-t border-gray-200 px-4 py-5 sm:px-6">
      <div class="pt-5">
        <div class="flex justify-end">
          <a href="{% url 'common:user-update' user.id %}" class="ml-3 inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
            {% translate "Change" %}</a>
          <a href="{% url 'common:user-delete' user.id %}" class="ml-3 bg-white py-2 px-4 border border-red-300 rounded-md shadow-sm text-sm font-medium text-red-700 hover:bg-red-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
            {% translate "Delete" %}
          </a>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}

common/templates/common/user_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load i18n %}
{% block title %}Objector + {% translate "User form" %} + {{ user }}{% endblock %}
{% block h1 %}{% translate "User form" %}{% endblock %}
{% block h2 %}{{ user }}{% endblock %}
{% block content %}
<form method="POST" enctype="multipart/form-data" class="space-y-8 divide-y divide-gray-200">{% csrf_token %}
  {{ form | crispy }}
  <div class="flex justify-end">
    <button type="submit" class="ml-3 inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
      {% translate "Save" %}
    </button>
    <a href="{% url 'common:user-detail' user.id %}" class="ml-3 bg-white py-2 px-4 border border-gray-300 rounded-md shadow-sm text-sm font-medium text-gray-700 hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
      {% translate "Cancel" %}
    </a>
  </div>
</form>
{% endblock %}