common/urls.py
from django.urls import path
from . import views

app_name = "common"

urlpatterns = [
    path("", views.HomeTemplateView.as_view(), name="home"),
    path("dashboard/", views.DashboardTemplateView.as_view(), name="dashboard"),
    path("logout/", views.LogoutRedirectView.as_view(), name="logout"),
    path("user/<int:pk>/", views.UserDetailView.as_view(), name="user-detail"),
    path("user/<int:pk>/change/", views.UserUpdateView.as_view(), name="user-update"),
    path("user/<int:pk>/delete/", views.UserDeleteView.as_view(), name="user-delete"),
]

inventory/urls.py
from django.urls import path
from . import views

app_name = "inventory"

urlpatterns = [
    path("location/", views.LocationListView.as_view(), name="location-list"),
    path("location/add/", views.LocationCreateView.as_view(), name="location-create"),
    path(
        "location/<int:pk>/", views.LocationDetailView.as_view(), name="location-detail"
    ),
    path(
        "location/<int:pk>/change/",
        views.LocationUpdateView.as_view(),
        name="location-update",
    ),
    path(
        "location/<int:pk>/delete/",
        views.LocationDeleteView.as_view(),
        name="location-delete",
    ),
    path("object/", views.ObjectFilterView.as_view(), name="object-list"),
    path("object/add/", views.ObjectCreateView.as_view(), name="object-create"),
    path("object/<int:pk>/", views.ObjectDetailView.as_view(), name="object-detail"),
    path(
        "object/<int:pk>/change/",
        views.ObjectUpdateView.as_view(),
        name="object-update",
    ),
    path(
        "object/<int:pk>/delete/",
        views.ObjectDeleteView.as_view(),
        name="object-delete",
    ),
    path("sensor/add/", views.SensorCreateView.as_view(), name="sensor-create"),
    path("sensor/", views.SensorFilterView.as_view(), name="sensor-list"),
    path(
        "sensor/<int:pk>/",
        views.SensorDetailView.as_view(),
        name="sensor-detail",
    ),
    path(
        "sensor/<int:pk>/change/",
        views.SensorUpdateView.as_view(),
        name="sensor-update",
    ),
    path(
        "sensor/<int:pk>/webhook/",
        views.SensorWebhookView.as_view(),
        name="sensor-webhook",
    ),
    path(
        "sensor/<int:pk>/delete/",
        views.SensorDeleteView.as_view(),
        name="sensor-delete",
    ),
]

maintenance/urls.py
from django.urls import path
from . import views

app_name = "maintenance"

urlpatterns = [
    path("task/", views.TaskFilterView.as_view(), name="task-list"),
    path(
        "task/add/",
        views.TaskCreateView.as_view(),
        name="task-create",
    ),
    path(
        "task/<int:pk>/",
        views.TaskDetailView.as_view(),
        name="task-detail",
    ),
    path(
        "task/<int:pk>/change/",
        views.TaskUpdateView.as_view(),
        name="task-update",
    ),
    path(
        "task/<int:pk>/delete/",
        views.TaskDeleteView.as_view(),
        name="task-delete",
    ),
    path("journal/", views.JournalFilterView.as_view(), name="journal-list"),
    path(
        "journal/add",
        views.JournalCreate.as_view(),
        name="journal-create",
    ),
    path(
        "journal/<int:pk>/",
        views.JournalDetailView.as_view(),
        name="journal-detail",
    ),
    path(
        "journal/<int:pk>/change/",
        views.JournalUpdateView.as_view(),
        name="journal-update",
    ),
    path(
        "journal/<int:pk>/delete/",
        views.JournalDeleteView.as_view(),
        name="journal-delete",
    ),
    path(
        "trigger/add",
        views.TriggerCreateView.as_view(),
        name="trigger-create",
    ),
    path(
        "trigger/<int:pk>/",
        views.TriggerDetailView.as_view(),
        name="trigger-detail",
    ),
    path(
        "trigger/<int:pk>/change/",
        views.TriggerUpdateView.as_view(),
        name="trigger-update",
    ),
    path(
        "trigger/<int:pk>/delete/",
        views.TriggerDeleteView.as_view(),
        name="trigger-delete",
    ),
    path(
        "document/add",
        views.DocumentCreateView.as_view(),
        name="document-create",
    ),
    path(
        "document/<int:pk>/",
        views.DocumentDetailView.as_view(),
        name="document-detail",
    ),
    path(
        "document/<int:pk>/change/",
        views.DocumentUpdateView.as_view(),
        name="document-update",
    ),
    path(
        "document/<int:pk>/delete/",
        views.DocumentDeleteView.as_view(),
        name="document-delete",
    ),
]

objector/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from django.utils.translation import gettext_lazy as _

admin.site.site_header = _("Objector admin")

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("social_django.urls")),
    path("", include("common.urls")),
    path("", include("inventory.urls")),
    path("", include("maintenance.urls")),
]

# add this lines
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

common/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils.translation import gettext_lazy as _
from rules.contrib.models import RulesModelMixin


class User(RulesModelMixin, AbstractUser):
    class Languages(models.TextChoices):
        GERMAN = "de", _("German")
        ENGLISH = "en", _("English")

    send_status_report_at = models.TimeField(
        _("Send status report at"), blank=True, null=True
    )
    status_report_last_sent_at = models.DateTimeField(
        _("Status report last sent at"), blank=True, null=True
    )
    status_report_language = models.CharField(
        _("Status report language"),
        choices=Languages.choices,
        default=Languages.ENGLISH,
        max_length=2,
    )

    def get_picture(self) -> str:
        social_user = self.social_auth.get()
        picture = social_user.extra_data.get("picture", "")
        return picture

    def get_absolute_url(self) -> str:
        return f"/user/{self.id}"

common/forms.py
from django import forms
from .models import User
from django.utils.translation import gettext_lazy as _


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = [
            "first_name",
            "last_name",
            "send_status_report_at",
            "status_report_language",
        ]

    send_status_report_at = forms.TimeField(
        label=_("Send status report at"),
        required=False,
        input_formats=["%H:%M"],
        widget=forms.TimeInput(
            attrs={
                "type": "time",
                "placeholder": "Select a time",
            },
            format="%H:%M",
        ),
    )

common/views.py
from django.contrib.auth import logout as django_logout
from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import (
    RedirectView,
    UpdateView,
    DetailView,
    DeleteView,
    TemplateView,
)
from django.db.models import Min, Max
from inventory.models import Location
from maintenance.models import Task
from inventory.models import Sensor
from django.utils import timezone
from rules.contrib.views import AutoPermissionRequiredMixin
from .models import User
from .forms import UserForm
from django.urls import reverse_lazy


class HomeTemplateView(TemplateView):
    template_name = "common/home.html"


class LogoutRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self, **kwargs) -> str:
        django_logout(self.request)
        domain = settings.SOCIAL_AUTH_AUTH0_DOMAIN
        client_id = settings.SOCIAL_AUTH_AUTH0_KEY
        return_to = self.request.build_absolute_uri("/")
        return f"https://{domain}/v2/logout?client_id={client_id}&returnTo={return_to}"


class DashboardTemplateView(LoginRequiredMixin, TemplateView):
    template_name = "common/dashboard.html"

    def get_context_data(self, *args, **kwargs) -> dict:
        context = super().get_context_data(**kwargs)
        groups = self.request.user.groups.values_list("pk", flat=True)
        groups_as_list = list(groups)
        overdue_tasks_queryset = (
            Task.objects.filter(
                object__owner=self.request.user, status=Task.Statuses.OVERDUE
            )
            | Task.objects.filter(
                object__management_group__in=groups_as_list,
                status=Task.Statuses.OVERDUE,
            )
            | Task.objects.filter(
                object__maintenance_group__in=groups_as_list,
                status=Task.Statuses.OVERDUE,
            )
        )
        due_tasks_queryset = (
            Task.objects.filter(
                object__owner=self.request.user, status=Task.Statuses.DUE
            )
            | Task.objects.filter(
                object__management_group__in=groups_as_list,
                status=Task.Statuses.DUE,
            )
            | Task.objects.filter(
                object__maintenance_group__in=groups_as_list,
                status=Task.Statuses.DUE,
            )
        )
        pending_tasks_queryset = (
            Task.objects.filter(
                object__owner=self.request.user, status=Task.Statuses.PENDING
            )
            | Task.objects.filter(
                object__management_group__in=groups_as_list,
                status=Task.Statuses.PENDING,
            )
            | Task.objects.filter(
                object__maintenance_group__in=groups_as_list,
                status=Task.Statuses.PENDING,
            )
        )
        red_sensors_queryset = (
            Sensor.objects.filter(
                object__owner=self.request.user, status=Sensor.Statuses.RED
            )
            | Sensor.objects.filter(
                object__management_group__in=groups_as_list, status=Sensor.Statuses.RED
            )
            | Sensor.objects.filter(
                object__maintenance_group__in=groups_as_list, status=Sensor.Statuses.RED
            )
        )
        amber_sensors_queryset = (
            Sensor.objects.filter(
                object__owner=self.request.user, status=Sensor.Statuses.AMBER
            )
            | Sensor.objects.filter(
                object__management_group__in=groups_as_list,
                status=Sensor.Statuses.AMBER,
            )
            | Sensor.objects.filter(
                object__maintenance_group__in=groups_as_list,
                status=Sensor.Statuses.AMBER,
            )
        )
        green_sensors_queryset = (
            Sensor.objects.filter(
                object__owner=self.request.user, status=Sensor.Statuses.GREEN
            )
            | Sensor.objects.filter(
                object__management_group__in=groups_as_list,
                status=Sensor.Statuses.GREEN,
            )
            | Sensor.objects.filter(
                object__maintenance_group__in=groups_as_list,
                status=Sensor.Statuses.GREEN,
            )
        )
        location_queryset = (
            Location.objects.filter(
                owner=self.request.user, latitude__isnull=False, longitude__isnull=False
            )
            | Location.objects.filter(
                management_group__in=groups_as_list,
                latitude__isnull=False,
                longitude__isnull=False,
            )
            | Location.objects.filter(
                maintenance_group__in=groups_as_list,
                latitude__isnull=False,
                longitude__isnull=False,
            )
        )
        context["overdue_tasks_count"] = overdue_tasks_queryset.count()
        context["due_tasks_count"] = due_tasks_queryset.count()
        context["pending_tasks_count"] = pending_tasks_queryset.count()
        context["red_sensors_count"] = red_sensors_queryset.count()
        context["amber_sensors_count"] = amber_sensors_queryset.count()
        context["green_sensors_count"] = green_sensors_queryset.count()
        context["locations"] = location_queryset
        context["locations_aggregates"] = location_queryset.aggregate(
            Min("latitude"), Max("latitude"), Min("longitude"), Max("longitude")
        )
        context["current_datetime"] = timezone.now()

        return context


class UserDetailView(AutoPermissionRequiredMixin, DetailView):
    model = User
    raise_exception = True


class UserUpdateView(AutoPermissionRequiredMixin, UpdateView):
    model = User
    raise_exception = True
    form_class = UserForm


class UserDeleteView(AutoPermissionRequiredMixin, DeleteView):
    model = User
    raise_exception = True
    success_url = reverse_lazy("home")

common/templates/base.html
{% load static %}
{% load i18n %}
{% load url_active %}
{% get_current_language as language %}
<!DOCTYPE html>
<html lang="{{ language }}">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="application-name" content="Objector">
  <meta name="apple-mobile-web-app-title" content="Objector">
  <meta name="theme-color" content="#4F46E5">
  <meta name="msapplication-navbutton-color" content="#4F46E5">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="msapplication-starturl" content="/">
  <title>{% block title %}Objector{% endblock %}</title>
  <link rel="manifest" href="{% static 'common/json/manifest.json' %}">
  <link rel="icon" href="{% static 'common/img/objector-icon-512x512.png' %}" sizes="512x512" type="image/png">
  <link rel="icon" href="{% static 'common/img/objector-icon-192x192.png' %}" sizes="192x192" type="image/png">
  <link rel="icon" href="{% static 'common/img/objector-icon-150x150.png' %}" sizes="150x150" type="image/png">
  <link rel="icon" href="{% static 'common/img/objector-icon-32x32.png' %}" sizes="32x32" type="image/png">
  <link rel="icon" href="{% static 'common/img/objector-icon-16x16.png' %}" sizes="16x16" type="image/png">
  <link rel="apple-touch-icon" href="{% static 'common/img/objector-icon-150x150.png' %}" sizes="512x512"
    type="image/png">
  <link rel="apple-touch-icon" href="{% static 'common/img/objector-icon-192x192.png' %}" sizes="192x192"
    type="image/png">
  <link rel="apple-touch-icon" href="{% static 'common/img/objector-icon-150x150.png' %}" sizes="150x150"
    type="image/png">
  {# https://www.srihash.org/ #}
  <script src="https://cdn.tailwindcss.com/3.2.6"></script>
  <script src="https://unpkg.com/alpinejs@3.12.0/dist/cdn.min.js" integrity="sha384-cNc6Ohk6WSbK+sByRXr9COZWTDVEag1x/Qb7jg15rtdQ4eOqYCfzwQGAxvoh+FQX" crossorigin="anonymous" defer></script>
  {% block head %}{% endblock %}
</head>

<body>
  <div class="min-h-screen bg-gray-100">
    <nav class="bg-white shadow" x-data="{mobilemenuopen: false, usermenuopen: false}">
      <div class="max-w-7xl mx-auto px-2 sm:px-6 lg:px-8">
        <div class="relative flex justify-between h-16">
          <div class="absolute inset-y-0 left-0 flex items-center sm:hidden">
            <!-- Mobile menu button -->
            <button type="button"
              class="inline-flex items-center justify-center p-2 rounded-md text-gray-400 hover:text-gray-500 hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-inset focus:ring-indigo-500"
              aria-controls="mobile-menu" @click="mobilemenuopen = !mobilemenuopen" x-bind:aria-expanded="mobilemenuopen.toString()">
              <span class="sr-only">Open main menu</span>
              <svg x-description="Icon when menu is closed. Heroicon name: outline/menu" x-state:on="Menu open" x-state:off="Menu closed" class="h-6 w-6 hidden"
                :class="{ 'hidden': mobilemenuopen, 'block': !(mobilemenuopen) }" xmlns="http://www.w3.org/2000/svg" fill="none"
                viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16">
                </path>
              </svg>
              <svg x-description="Icon when menu is open. Heroicon name: outline/x" x-state:on="Menu open" x-state:off="Menu closed" class="h-6 w-6 block"
                :class="{ 'block': mobilemenuopen, 'hidden': !(mobilemenuopen) }" xmlns="http://www.w3.org/2000/svg" fill="none"
                viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"></path>
              </svg>
            </button>
          </div>
          <div class="flex-1 flex items-center justify-center sm:items-stretch sm:justify-start">
            <div class="flex-shrink-0 flex items-center">
              <a href="{% url 'common:home' %}"><img class="block lg:hidden h-8 w-auto" src="{% static 'common/img/objector-mark.svg' %}" alt="Objector"></a>
              <a href="{% url 'common:home' %}"><img class="hidden lg:block h-8 w-auto" src="{% static 'common/img/objector-logo.svg' %}" alt="Objector"></a>
            </div>
            <div class="hidden sm:ml-6 sm:flex sm:space-x-8">
              {% if user.is_authenticated %}
              <a href="{% url 'common:dashboard' %}" class="{% url_active 'common:dashboard' %} border-transparent hover:text-gray-700 hover:border-gray-300 inline-flex items-center px-1 pt-1 border-b-2 text-sm font-medium">{% translate "Dashboard" %}</a>
              <a href="{% url 'inventory:location-list' %}" class="{% url_active 'inventory:location-list' %} border-transparent hover:text-gray-700 hover:border-gray-300 inline-flex items-center px-1 pt-1 border-b-2 text-sm font-medium">{% translate "Location" %}</a>
              <a href="{% url 'inventory:object-list' %}" class="{% url_active 'inventory:object-list' %} border-transparent hover:text-gray-700 hover:border-gray-300 inline-flex items-center px-1 pt-1 border-b-2 text-sm font-medium">{% translate "Object" %}</a>
              <a href="{% url 'inventory:sensor-list' %}" class="{% url_active 'inventory:sensor-list' %} border-transparent hover:text-gray-700 hover:border-gray-300 inline-flex items-center px-1 pt-1 border-b-2 text-sm font-medium">{% translate "Sensor" %}</a>
              <a href="{% url 'maintenance:task-list' %}" class="{% url_active 'maintenance:task-list' %} border-transparent hover:text-gray-700 hover:border-indigo-300 inline-flex items-center px-1 pt-1 border-b-2 text-sm font-medium">{% translate "Task" %}</a>
              <a href="{% url 'maintenance:journal-list' %}" class="{% url_active 'maintenance:journal-list' %} border-transparent hover:text-gray-700 hover:border-indigo-300 inline-flex items-center px-1 pt-1 border-b-2 text-sm font-medium">{% translate "Journal" %}</a>
              {% endif %}
            </div>
          </div>
          <div class="absolute inset-y-0 right-0 flex items-center pr-2 sm:static sm:inset-auto sm:ml-6 sm:pr-0">
            {% if user.is_authenticated %}
            <div class="ml-3 relative flex-shrink-0">
              <div>
                <button type="button" class="bg-gray-50 rounded-full flex text-sm text-white focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-gray-50 focus:ring-purple-500" id="user-menu-button" aria-expanded="false" aria-haspopup="true"  @click="usermenuopen = !usermenuopen">
                  <span class="sr-only">Open user menu</span>
                  {% if user.get_picture %}
                  <img class="rounded-full h-8 w-8" src="{{ user.get_picture }}" alt="">
                  {% else %}
                  <span class="inline-block h-8 w-8 rounded-full overflow-hidden bg-gray-100">
                    <svg class="h-full w-full text-gray-300" fill="currentColor" viewBox="0 0 24 24">
                      <path d="M24 20.993V24H0v-2.996A14.977 14.977 0 0112.004 15c4.904 0 9.26 2.354 11.996 5.993zM16.002 8.999a4 4 0 11-8 0 4 4 0 018 0z" />
                    </svg>
                  </span>
                  {% endif %}
                </button>
              </div>
              <div class="origin-top-right absolute z-10 right-0 mt-2 w-48 rounded-md shadow-lg py-1 bg-white ring-1 ring-black ring-opacity-5 focus:outline-none" role="menu" aria-orientation="vertical" aria-labelledby="user-menu-button" tabindex="-1" x-show="usermenuopen">
                {% if user.is_staff %}
                <a href="/admin/" target="_blank" class="block py-2 px-4 text-sm text-gray-700">{% translate "Admin" %}</a>
                {% endif %}
                <a href="{% url 'common:user-detail' user.id %}" class="block py-2 px-4 text-sm text-gray-700" role="menuitem" tabindex="-1" id="user-menu-item-0"> {% translate "Profile" %} </a>
                <a href="/logout" class="block py-2 px-4 text-sm text-gray-700" role="menuitem" tabindex="-1" id="user-menu-item-2"> {% translate "Log out" %} </a>
              </div>
            </div>
            {% else %}
            <a href="/login/auth0" class="relative inline-flex items-center px-4 py-2 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-green-600 hover:bg-green-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
              {% translate "Log in" %}
            </a>
            {% endif %}
          </div>
        </div>
        <div x-description="Mobile menu, show/hide based on menu state." class="sm:hidden" id="mobile-menu"
          x-show="mobilemenuopen" style="display: none;">
          <div class="pt-2 pb-4 space-y-1">
            <!-- Current: "bg-indigo-50 border-indigo-500 text-indigo-700", Default: "border-transparent text-gray-500 hover:bg-gray-50 hover:border-gray-300 hover:text-gray-700" -->
            {% if user.is_authenticated %}
            <a href="{% url 'common:dashboard' %}" class="{% url_active 'common:dashboard' %} border-transparent hover:text-gray-700 hover:border-gray-300 block pl-3 pr-4 py-2 border-l-2 text-base font-medium">{% translate "Dashboard" %}</a>
            <a href="{% url 'inventory:location-list' %}" class="{% url_active 'inventory:location-list' %} border-transparent hover:text-gray-700 hover:border-gray-300 block pl-3 pr-4 py-2 border-l-2 text-base font-medium">{% translate "Location" %}</a>
            <a href="{% url 'inventory:object-list' %}" class="{% url_active 'inventory:object-list' %} border-transparent hover:text-gray-700 hover:border-gray-300 block pl-3 pr-4 py-2 border-l-2 text-base font-medium">{% translate "Object" %}</a>
            <a href="{% url 'inventory:sensor-list' %}" class="{% url_active 'inventory:sensor-list' %} border-transparent hover:text-gray-700 hover:border-gray-300 block pl-3 pr-4 py-2 border-l-2 text-base font-medium">{% translate "Sensor" %}</a>
            <a href="{% url 'maintenance:task-list' %}" class="{% url_active 'maintenance:task-list' %} border-transparent hover:text-gray-700 hover:border-gray-300 block pl-3 pr-4 py-2 border-l-2 text-base font-medium">{% translate "Task" %}</a>
            <a href="{% url 'maintenance:journal-list' %}" class="{% url_active 'maintenance:journal-list' %} border-transparent hover:text-gray-700 hover:border-gray-300 block pl-3 pr-4 py-2 border-l-2 text-base font-medium">{% translate "Journal" %}</a>
            {% endif %}
          </div>
        </div>
      </div>
    </nav>
    <div class="py-10">
      <header>
        <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <h1 class="text-2xl font-bold leading-tight text-gray-900">
            {% block h1 %}{% endblock %}
          </h1>
          <h2 class="text-lg font-bold leading-tight text-gray-500">
            {% block h2 %}{% endblock %}
          </h2>
        </div>
      </header>
      <main>
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
          <div class="px-4 py-8 sm:px-0 text-base">
            {% block content %}{% endblock %}
          </div>
        </div>
      </main>
    </div>
  </div>
  <footer class="bg-white">
    <div class="max-w-7xl mx-auto py-12 px-4 sm:px-6 md:flex md:items-center md:justify-between lg:px-8">
      <div class="flex justify-center space-x-6 md:order-2">
        <a href="https://github.com/gldecurtins/objector" target="_blank" rel="noreferrer noopener"
          class="text-gray-400 hover:text-gray-500">
          <span class="sr-only">GitHub</span>
          <svg class="h-6 w-6" fill="currentColor" viewBox="0 0 24 24" aria-hidden="true">
            <path fill-rule="evenodd"
              d="M12 2C6.477 2 2 6.484 2 12.017c0 4.425 2.865 8.18 6.839 9.504.5.092.682-.217.682-.483 0-.237-.008-.868-.013-1.703-2.782.605-3.369-1.343-3.369-1.343-.454-1.158-1.11-1.466-1.11-1.466-.908-.62.069-.608.069-.608 1.003.07 1.531 1.032 1.531 1.032.892 1.53 2.341 1.088 2.91.832.092-.647.35-1.088.636-1.338-2.22-.253-4.555-1.113-4.555-4.951 0-1.093.39-1.988 1.029-2.688-.103-.253-.446-1.272.098-2.65 0 0 .84-.27 2.75 1.026A9.564 9.564 0 0112 6.844c.85.004 1.705.115 2.504.337 1.909-1.296 2.747-1.027 2.747-1.027.546 1.379.202 2.398.1 2.651.64.7 1.028 1.595 1.028 2.688 0 3.848-2.339 4.695-4.566 4.943.359.309.678.92.678 1.855 0 1.338-.012 2.419-.012 2.747 0 .268.18.58.688.482A10.019 10.019 0 0022 12.017C22 6.484 17.522 2 12 2z"
              clip-rule="evenodd" />
          </svg>
        </a>
      </div>
      <div class="mt-8 md:mt-0 md:order-1">
        <p class="text-center text-base text-gray-400">
          &copy; 2022, Gian Luca Decurtins. All rights reserved.
        </p>
      </div>
    </div>
  </footer>
</body>

</html>