common/urls.py
from django.urls import path
from . import views

app_name = "common"

urlpatterns = [
    path("", views.HomeTemplateView.as_view(), name="home"),
    path("dashboard/", views.DashboardTemplateView.as_view(), name="dashboard"),
    path("logout/", views.LogoutRedirectView.as_view(), name="logout"),
    path("user/<int:pk>/", views.UserDetailView.as_view(), name="user-detail"),
    path("user/<int:pk>/change/", views.UserUpdateView.as_view(), name="user-update"),
    path("user/<int:pk>/delete/", views.UserDeleteView.as_view(), name="user-delete"),
]

inventory/urls.py
from django.urls import path
from . import views

app_name = "inventory"

urlpatterns = [
    path("location/", views.LocationListView.as_view(), name="location-list"),
    path("location/add/", views.LocationCreateView.as_view(), name="location-create"),
    path(
        "location/<int:pk>/", views.LocationDetailView.as_view(), name="location-detail"
    ),
    path(
        "location/<int:pk>/change/",
        views.LocationUpdateView.as_view(),
        name="location-update",
    ),
    path(
        "location/<int:pk>/delete/",
        views.LocationDeleteView.as_view(),
        name="location-delete",
    ),
    path("object/", views.ObjectFilterView.as_view(), name="object-list"),
    path("object/add/", views.ObjectCreateView.as_view(), name="object-create"),
    path("object/<int:pk>/", views.ObjectDetailView.as_view(), name="object-detail"),
    path(
        "object/<int:pk>/change/",
        views.ObjectUpdateView.as_view(),
        name="object-update",
    ),
    path(
        "object/<int:pk>/delete/",
        views.ObjectDeleteView.as_view(),
        name="object-delete",
    ),
    path("sensor/add/", views.SensorCreateView.as_view(), name="sensor-create"),
    path("sensor/", views.SensorFilterView.as_view(), name="sensor-list"),
    path(
        "sensor/<int:pk>/",
        views.SensorDetailView.as_view(),
        name="sensor-detail",
    ),
    path(
        "sensor/<int:pk>/change/",
        views.SensorUpdateView.as_view(),
        name="sensor-update",
    ),
    path(
        "sensor/<int:pk>/webhook/",
        views.SensorWebhookView.as_view(),
        name="sensor-webhook",
    ),
    path(
        "sensor/<int:pk>/delete/",
        views.SensorDeleteView.as_view(),
        name="sensor-delete",
    ),
]

maintenance/urls.py
from django.urls import path
from . import views

app_name = "maintenance"

urlpatterns = [
    path("task/", views.TaskFilterView.as_view(), name="task-list"),
    path(
        "task/add/",
        views.TaskCreateView.as_view(),
        name="task-create",
    ),
    path(
        "task/<int:pk>/",
        views.TaskDetailView.as_view(),
        name="task-detail",
    ),
    path(
        "task/<int:pk>/change/",
        views.TaskUpdateView.as_view(),
        name="task-update",
    ),
    path(
        "task/<int:pk>/delete/",
        views.TaskDeleteView.as_view(),
        name="task-delete",
    ),
    path("journal/", views.JournalFilterView.as_view(), name="journal-list"),
    path(
        "journal/add",
        views.JournalCreate.as_view(),
        name="journal-create",
    ),
    path(
        "journal/<int:pk>/",
        views.JournalDetailView.as_view(),
        name="journal-detail",
    ),
    path(
        "journal/<int:pk>/change/",
        views.JournalUpdateView.as_view(),
        name="journal-update",
    ),
    path(
        "journal/<int:pk>/delete/",
        views.JournalDeleteView.as_view(),
        name="journal-delete",
    ),
    path(
        "trigger/add",
        views.TriggerCreateView.as_view(),
        name="trigger-create",
    ),
    path(
        "trigger/<int:pk>/",
        views.TriggerDetailView.as_view(),
        name="trigger-detail",
    ),
    path(
        "trigger/<int:pk>/change/",
        views.TriggerUpdateView.as_view(),
        name="trigger-update",
    ),
    path(
        "trigger/<int:pk>/delete/",
        views.TriggerDeleteView.as_view(),
        name="trigger-delete",
    ),
    path(
        "document/add",
        views.DocumentCreateView.as_view(),
        name="document-create",
    ),
    path(
        "document/<int:pk>/",
        views.DocumentDetailView.as_view(),
        name="document-detail",
    ),
    path(
        "document/<int:pk>/change/",
        views.DocumentUpdateView.as_view(),
        name="document-update",
    ),
    path(
        "document/<int:pk>/delete/",
        views.DocumentDeleteView.as_view(),
        name="document-delete",
    ),
]

objector/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from django.utils.translation import gettext_lazy as _

admin.site.site_header = _("Objector admin")

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("social_django.urls")),
    path("", include("common.urls")),
    path("", include("inventory.urls")),
    path("", include("maintenance.urls")),
]

# add this lines
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

inventory/models.py
from django.db import models
from django.conf import settings
from rules.contrib.models import RulesModel
from django.contrib.auth.models import Group
from django.utils.translation import gettext_lazy as _


def location_image_upload_handler(instance, filename) -> str:
    return f"location/{instance.id}/image/{filename}"


def object_image_upload_handler(instance, filename) -> str:
    return f"object/{instance.id}/image/{filename}"


class Location(RulesModel):
    class Statuses(models.IntegerChoices):
        RED = 10, _("Alert")
        AMBER = 20, _("Warning")
        GREEN = 30, _("Normal")

    name = models.CharField(_("Name"), max_length=200)
    description = models.TextField(_("Description"), blank=True)
    image = models.ImageField(
        _("Image"), upload_to=location_image_upload_handler, blank=True, null=True
    )
    address = models.TextField(_("Address"), blank=True)
    latitude = models.FloatField(_("Latitude"), blank=True, null=True)
    longitude = models.FloatField(_("Longitude"), blank=True, null=True)
    status = models.PositiveSmallIntegerField(
        _("Status"), choices=Statuses.choices, default=Statuses.GREEN
    )
    owner = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        verbose_name=_("Owner"),
        related_name="location_owner",
        on_delete=models.CASCADE,
        help_text=_("Owner can view, change or delete this location."),
    )
    management_group = models.ForeignKey(
        Group,
        verbose_name=_("Management group"),
        related_name="location_management_group",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        help_text=_("Group members can view, change or delete this location."),
    )
    maintenance_group = models.ForeignKey(
        Group,
        verbose_name=_("Maintenance group"),
        related_name="location_maintenance_group",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        help_text=_("Group members can view this location."),
    )
    created_at = models.DateTimeField(_("Created at"), auto_now_add=True)
    updated_at = models.DateTimeField(_("Updated at"), auto_now=True)
    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        verbose_name=_("Created by"),
        related_name="location_created_by",
        on_delete=models.SET_NULL,
        null=True,
    )
    updated_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        verbose_name=_("Updated by"),
        related_name="location_updated_by",
        on_delete=models.SET_NULL,
        null=True,
    )

    class Meta:
        verbose_name = _("Location")
        verbose_name_plural = _("Locations")
        ordering = ["status", "name"]
        indexes = [
            models.Index(fields=["owner", "management_group", "maintenance_group"]),
        ]

    def __str__(self) -> str:
        return self.name

    def get_absolute_url(self) -> str:
        return f"/location/{self.id}"

    @property
    def status_color(self) -> str:
        status_color = "green"
        if self.status == self.Statuses.RED:
            status_color = "red"
        elif self.status == self.Statuses.AMBER:
            status_color = "amber"
        return status_color


class Object(RulesModel):
    class Statuses(models.IntegerChoices):
        RED = 10, _("Alert")
        AMBER = 20, _("Warning")
        GREEN = 30, _("Normal")

    name = models.CharField(_("Name"), max_length=200)
    description = models.TextField(_("Description"), blank=True)
    image = models.ImageField(
        _("Image"), upload_to=object_image_upload_handler, blank=True, null=True
    )
    location = models.ForeignKey(
        Location,
        verbose_name=_("Location"),
        related_name="object_location",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
    )
    status = models.PositiveSmallIntegerField(
        _("Status"), choices=Statuses.choices, default=Statuses.GREEN
    )
    owner = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        verbose_name=_("Owner"),
        related_name="object_owner",
        on_delete=models.CASCADE,
        help_text=_("Owner can view, change or delete this object."),
    )
    management_group = models.ForeignKey(
        Group,
        verbose_name=_("Management group"),
        related_name="object_management_group",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        help_text=_("Group members can view or update this object."),
    )
    maintenance_group = models.ForeignKey(
        Group,
        verbose_name=_("Maintenance group"),
        related_name="object_maintenance_group",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        help_text=_("Group members can view this object."),
    )
    created_at = models.DateTimeField(_("Created at"), auto_now_add=True)
    updated_at = models.DateTimeField(_("Updated at"), auto_now=True)
    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        verbose_name=_("Created by"),
        related_name="object_created_by",
        on_delete=models.SET_NULL,
        null=True,
    )
    updated_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        verbose_name=_("Updated by"),
        related_name="object_updated_by",
        on_delete=models.SET_NULL,
        null=True,
    )

    class Meta:
        verbose_name = _("Object")
        verbose_name_plural = _("Objects")
        ordering = ["status", "name"]
        indexes = [
            models.Index(fields=["owner", "management_group", "maintenance_group"]),
        ]

    def __str__(self) -> str:
        str = self.name
        if self.location:
            str = f"{str} @{self.location}"
        return str

    def get_absolute_url(self) -> str:
        return f"/object/{self.id}"

    @property
    def status_color(self) -> str:
        status_color = "green"
        if self.status == self.Statuses.RED:
            status_color = "red"
        elif self.status == self.Statuses.AMBER:
            status_color = "amber"
        return status_color


class Sensor(RulesModel):
    class Statuses(models.IntegerChoices):
        RED = 10, _("Alert")
        AMBER = 20, _("Warning")
        GREEN = 30, _("Normal")

    name = models.CharField(_("Name"), max_length=200)
    description = models.TextField(_("Description"), blank=True)
    image = models.ImageField(
        _("Image"), upload_to=object_image_upload_handler, blank=True, null=True
    )
    object = models.ForeignKey(
        Object,
        verbose_name=_("Object"),
        related_name="sensor_object",
        on_delete=models.CASCADE,
    )
    status = models.PositiveSmallIntegerField(
        _("Status"), choices=Statuses.choices, default=Statuses.GREEN
    )
    webhook_authorization = models.CharField(
        _("Webhook authorization"), max_length=255, blank=True
    )
    webhook_payload = models.JSONField(_("Webhook payload"), blank=True, null=True)
    created_at = models.DateTimeField(_("Created at"), auto_now_add=True)
    updated_at = models.DateTimeField(_("Updated at"), auto_now=True)
    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        verbose_name=_("Created by"),
        related_name="sensor_created_by",
        on_delete=models.SET_NULL,
        null=True,
    )
    updated_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        verbose_name=_("Updated by"),
        related_name="sensor_updated_by",
        on_delete=models.SET_NULL,
        null=True,
    )

    class Meta:
        verbose_name = _("Sensor")
        verbose_name_plural = _("Sensors")
        ordering = ["status", "name"]

    def __str__(self) -> str:
        return self.name

    def get_absolute_url(self) -> str:
        return f"/sensor/{self.id}"

    def save(self, *args, **kwargs):
        self.set_sensor_status()
        super().save(*args, **kwargs)

    def set_sensor_status(self) -> None:
        sensor_status = self.Statuses.GREEN

        from maintenance.models import Trigger

        triggers = Trigger.objects.filter(sensor=self.id)

        for trigger in triggers:
            trigger.set_trigger_status_and_sensor_value(self.webhook_payload)

            if sensor_status > trigger.status:
                sensor_status = trigger.status

        self.status = sensor_status

    @property
    def status_color(self) -> str:
        status_color = "green"
        if self.status == self.Statuses.RED:
            status_color = "red"
        elif self.status == self.Statuses.AMBER:
            status_color = "amber"
        return status_color

inventory/forms.py
from django import forms
from .models import Location, Object, Sensor


class ObjectForm(forms.ModelForm):
    class Meta:
        model = Object
        fields = [
            "location",
            "name",
            "description",
            "owner",
            "management_group",
            "maintenance_group",
        ]

    def __init__(self, *args, **kwargs) -> None:
        self.request = kwargs.pop("request")
        super().__init__(*args, **kwargs)

        # all groups for user
        groups = self.request.user.groups.values_list("pk", flat=True)
        groups_as_list = list(groups)
        location_queryset = Location.objects.filter(
            owner=self.request.user
        ) | Location.objects.filter(management_group__in=groups_as_list)

        self.fields["location"].queryset = location_queryset


class SensorForm(forms.ModelForm):
    class Meta:
        model = Sensor
        fields = [
            "object",
            "name",
            "description",
            "image",
        ]

    def __init__(self, *args, **kwargs) -> None:
        self.request = kwargs.pop("request")
        super().__init__(*args, **kwargs)

        # all groups for user
        groups = self.request.user.groups.values_list("pk", flat=True)
        groups_as_list = list(groups)
        object_queryset = Object.objects.filter(
            owner=self.request.user
        ) | Object.objects.filter(management_group__in=groups_as_list)

        self.fields["object"].queryset = object_queryset

inventory/templates/inventory/location_detail.html
{% extends "base.html" %}
{% load i18n %}
{% load rules %}
{% block title %}Objector + {% translate "Location detail" %} + {{ location }}{% endblock %}
{% block h1 %}{% translate "Location detail" %}{% endblock %}
{% block h2 %}{{ location }}{% endblock %}
{% block content %}
<section aria-labelledby="location-detail-title">
  <div class="bg-white shadow sm:rounded-lg">
    <div class="border-t border-gray-200 px-4 py-5 sm:px-6">
      <dl class="grid grid-cols-1 gap-x-4 gap-y-8 sm:grid-cols-2">
        <div class="sm:col-span-1">
          <dt class="text-sm font-medium text-gray-500">
            {% translate "Name" %}
          </dt>
          <dd class="mt-1 text-sm text-gray-900">
            {{ location.name }}
          </dd>
        </div>
        <div class="sm:col-span-1">
          <dt class="text-sm font-medium text-gray-500">
            {% translate "Status" %}
          </dt>
          <dd class="mt-1 text-sm text-gray-900">
            <div
              class="inline-flex items-baseline px-2.5 py-0.5 rounded-full bg-{{ location.status_color }}-100 text-{{ location.status_color }}-800">
              {{ location.get_status_display }}
            </div>
          </dd>
        </div>
        <div class="sm:col-span-2">
          <dt class="text-sm font-medium text-gray-500">
            {% translate "Description" %}
          </dt>
          <dd class="mt-1 text-sm text-gray-900">
            {{ location.description|linebreaksbr }}
          </dd>
        </div>
      </dl>
    </div>
    <div class="border-t border-gray-200 px-4 py-5 sm:px-6">
      <dl class="grid grid-cols-1 gap-x-4 gap-y-8 sm:grid-cols-2">
        <div class="sm:col-span-2">
          <dt class="text-sm font-medium text-gray-500">
            {% translate "Address" %}
          </dt>
          <dd class="mt-1 text-sm text-gray-900">
            {{ location.address|linebreaksbr }}
          </dd>
        </div>
        <div class="sm:col-span-1">
          <dt class="text-sm font-medium text-gray-500">
            {% translate "Latitude" %}
          </dt>
          <dd class="mt-1 text-sm text-gray-900">
            {{ location.latitude }}
          </dd>
        </div>
        <div class="sm:col-span-1">
          <dt class="text-sm font-medium text-gray-500">
            {% translate "Longitude" %}
          </dt>
          <dd class="mt-1 text-sm text-gray-900">
            {{ location.longitude }}
          </dd>
        </div>
      </dl>
    </div>
    <div class="border-t border-gray-200 px-4 py-5 sm:px-6">
      <dl class="grid grid-cols-1 gap-x-4 gap-y-8 sm:grid-cols-2">
        <div class="sm:col-span-2">
          <dt class="text-sm font-medium text-gray-500">
            {% translate "Owner" %}
          </dt>
          <dd class="mt-1 text-sm text-gray-900">
            {{ location.owner }}
          </dd>
        </div>
        <div class="sm:col-span-1">
          <dt class="text-sm font-medium text-gray-500">
            {% translate "Management group" %}
          </dt>
          <dd class="mt-1 text-sm text-gray-900">
            {{ location.management_group }}
          </dd>
        </div>
        <div class="sm:col-span-1">
          <dt class="text-sm font-medium text-gray-500">
            {% translate "Maintenance group" %}
          </dt>
          <dd class="mt-1 text-sm text-gray-900">
            {{ location.maintenance_group }}
          </dd>
        </div>
      </dl>
    </div>
    <div class="border-t border-gray-200 px-4 py-5 sm:px-6">
      <dl class="grid grid-cols-1 gap-x-4 gap-y-8 sm:grid-cols-2">
        <div class="sm:col-span-1">
          <dt class="text-sm font-medium text-gray-500">
            {% translate "Created at" %}
          </dt>
          <dd class="mt-1 text-sm text-gray-900">
            {{ location.created_at }}
          </dd>
        </div>
        <div class="sm:col-span-1">
          <dt class="text-sm font-medium text-gray-500">
            {% translate "Updated at" %}
          </dt>
          <dd class="mt-1 text-sm text-gray-900">
            {{ location.updated_at }}
          </dd>
        </div>
        <div class="sm:col-span-1">
          <dt class="text-sm font-medium text-gray-500">
            {% translate "Created by" %}
          </dt>
          <dd class="mt-1 text-sm text-gray-900">
            {{ location.created_by }}
          </dd>
        </div>
        <div class="sm:col-span-1">
          <dt class="text-sm font-medium text-gray-500">
            {% translate "Updated by" %}
          </dt>
          <dd class="mt-1 text-sm text-gray-900">
            {{ location.updated_by }}
          </dd>
        </div>
      </dl>
    </div>
    <div class="border-t border-gray-200 px-4 py-5 sm:px-6">
      <div class="pt-5">
        <div class="flex justify-end">
          <a href="{% url 'maintenance:journal-list' %}?object__location={{ location.id }}" class="ml-3 bg-white py-2 px-4 border border-gray-300 rounded-md shadow-sm text-sm font-medium text-gray-700 hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
            {% translate "Journal" %}
          </a>
          {% has_perm 'inventory.change_location' user location as can_change_location %}
          {% if can_change_location %}
          <a href="{% url 'inventory:location-update' location.id %}" class="ml-3 inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
            {% translate "Change" %}
          </a>
          {% endif %}
          {% has_perm 'inventory.delete_location' user location as can_delete_location %}
          {% if can_delete_location %}
          <a href="{% url 'inventory:location-delete' location.id %}" class="ml-3 bg-white py-2 px-4 border border-red-300 rounded-md shadow-sm text-sm font-medium text-red-700 hover:bg-red-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
            {% translate "Delete" %}
          </a>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
  <div class="px-4 py-5 sm:px-6">
    <h2 id="object-detail-title" class="text-lg leading-6 font-medium text-gray-900">
      {% translate "Objects" %}
    </h2>
  </div>
  {% if object_list %}
  <div class="flex flex-col">
    <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
      <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
        <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
          <table class="min-w-full divide-y divide-gray-200">
            <thead class="bg-gray-50">
              <tr>
                <th scope="col" class="whitespace-nowrap py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-6">
                  {% translate "Name" %}
                </th>
                <th scope="col" class="whitespace-nowrap px-2 py-3.5 text-left text-sm font-semibold text-gray-900">
                  {% translate "Description" %}
                </th>
                <th scope="col" class="whitespace-nowrap px-2 py-3.5 text-left text-sm font-semibold text-gray-900 hidden md:table-cell">
                  {% translate "Updated at" %}
                </th>
                <th scope="col" class="relative whitespace-nowrap py-3.5 pl-3 pr-4 sm:pr-6 hidden lg:table-cell">
                  <span class="sr-only">{% translate "Action" %}</span>
                </th>
              </tr>
            </thead>
            <tbody>
              {% for object in object_list %}
              <tr class="bg-white">
                <td class="whitespace-nowrap py-2 pl-4 pr-3 text-sm text-gray-500 sm:pl-6">
                  <div class="inline-flex items-baseline px-2.5 py-0.5 rounded-full bg-{{ object.status_color }}-100 text-{{ object.status_color }}-800">
                    <a href="{% url 'inventory:object-detail' object.id %}">{{ object.name }}</a>
                  </div>
                </td>
                <td class="whitespace-nowrap px-2 py-2 text-sm text-gray-500">
                  {{ object.description|truncatechars:20 }}
                </td>
                <td class="whitespace-nowrap px-2 py-2 text-sm text-gray-500 hidden md:table-cell">
                  {{ object.updated_at }}
                </td>
                <td class="relative whitespace-nowrap py-2 pl-3 pr-4 text-right text-sm font-medium sm:pr-6 hidden lg:table-cell">
                  <div class="ml-4 flex-shrink-0 flex space-x-4 justify-end">
                    {% has_perm 'inventory.view_object' user object as can_view_object %}
                    {% if can_view_object %}
                    <a href="{% url 'inventory:object-detail' object.id %}"  class="text-indigo-600 hover:text-indigo-900">
                      {% translate "View" %}
                    </a>
                    {% endif %}
                    {% has_perm 'inventory.change_object' user object as can_change_object %}
                    {% if can_change_object %}
                    <a href="{% url 'inventory:object-update' object.id %}" class="text-indigo-600 hover:text-indigo-900">
                      {% translate "Change" %}
                    </a>
                    {% endif %}
                    {% has_perm 'inventory.delete_object' user object as can_delete_object %}
                    {% if can_delete_object %}
                    <a href="{% url 'inventory:object-delete' object.id %}" class="text-indigo-600 hover:text-indigo-900">
                      {% translate "Delete" %}
                    </a>
                    {% endif %}
                  </div>
                </td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
  {% endif %}
  <div class="px-4 py-3 bg-gray-50 text-right sm:px-6">
    <a href="{% url 'inventory:object-create' %}?location={{ location.id }}" class="inline-flex items-center p-2 border border-transparent rounded-full shadow-sm text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
      <!-- Heroicon name: outline/plus-sm -->
      <svg class="h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 6v6m0 0v6m0-6h6m-6 0H6" />
      </svg>
    </a>
  </div>
</section>
{% endblock %}

inventory/templates/inventory/location_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load i18n %}
{% block title %}Objector + {% translate "Location form" %} + {{ location }}{% endblock %}
{% block h1 %}{% translate "Location form" %}{% endblock %}
{% block h2 %}{{ location }}{% endblock %}
{% block content %}
<form method="POST" enctype="multipart/form-data" class="space-y-8 divide-y divide-gray-200">{% csrf_token %}
  {{ form | crispy }}
  <div class="flex justify-end">
    <button type="submit" class="ml-3 inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
      {% translate "Save" %}
    </button>
    <a href="{% if location.id %}{% url 'inventory:location-detail' location.id %}{% else %}{% url 'inventory:location-list' %}{% endif %}" class="ml-3 bg-white py-2 px-4 border border-gray-300 rounded-md shadow-sm text-sm font-medium text-gray-700 hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
      {% translate "Cancel" %}
    </a>
  </div>
</form>
{% endblock %}

inventory/templates/inventory/object_form.html
{% extends "base.html" %}
{% load i18n %}
{% load crispy_forms_tags %}
{% block title %}Objector + {% translate "Object form" %} + {{ object }}{% endblock %}
{% block h1 %}{% translate "Object form" %}{% endblock %}
{% block h2 %}{{ object }}{% endblock %}
{% block content %}
<form method="POST" enctype="multipart/form-data" class="space-y-8 divide-y divide-gray-200">{% csrf_token %}
  {{ form | crispy }}
  <div class="flex justify-end">
    <button type="submit" class="ml-3 inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
      {% translate "Save" %}
    </button>
    <a href="{% if object.id %}{% url 'inventory:object-detail' object.id %}{% else %}{% url 'inventory:object-list' %}{% endif %}" class="ml-3 bg-white py-2 px-4 border border-gray-300 rounded-md shadow-sm text-sm font-medium text-gray-700 hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
      {% translate "Cancel" %}
    </a>
  </div>
</form>
{% endblock %}