common/urls.py
from django.urls import path
from . import views

app_name = "common"

urlpatterns = [
    path("", views.HomeTemplateView.as_view(), name="home"),
    path("dashboard/", views.DashboardTemplateView.as_view(), name="dashboard"),
    path("logout/", views.LogoutRedirectView.as_view(), name="logout"),
    path("user/<int:pk>/", views.UserDetailView.as_view(), name="user-detail"),
    path("user/<int:pk>/change/", views.UserUpdateView.as_view(), name="user-update"),
    path("user/<int:pk>/delete/", views.UserDeleteView.as_view(), name="user-delete"),
]

inventory/urls.py
from django.urls import path
from . import views

app_name = "inventory"

urlpatterns = [
    path("location/", views.LocationListView.as_view(), name="location-list"),
    path("location/add/", views.LocationCreateView.as_view(), name="location-create"),
    path(
        "location/<int:pk>/", views.LocationDetailView.as_view(), name="location-detail"
    ),
    path(
        "location/<int:pk>/change/",
        views.LocationUpdateView.as_view(),
        name="location-update",
    ),
    path(
        "location/<int:pk>/delete/",
        views.LocationDeleteView.as_view(),
        name="location-delete",
    ),
    path("object/", views.ObjectFilterView.as_view(), name="object-list"),
    path("object/add/", views.ObjectCreateView.as_view(), name="object-create"),
    path("object/<int:pk>/", views.ObjectDetailView.as_view(), name="object-detail"),
    path(
        "object/<int:pk>/change/",
        views.ObjectUpdateView.as_view(),
        name="object-update",
    ),
    path(
        "object/<int:pk>/delete/",
        views.ObjectDeleteView.as_view(),
        name="object-delete",
    ),
    path("sensor/add/", views.SensorCreateView.as_view(), name="sensor-create"),
    path("sensor/", views.SensorFilterView.as_view(), name="sensor-list"),
    path(
        "sensor/<int:pk>/",
        views.SensorDetailView.as_view(),
        name="sensor-detail",
    ),
    path(
        "sensor/<int:pk>/change/",
        views.SensorUpdateView.as_view(),
        name="sensor-update",
    ),
    path(
        "sensor/<int:pk>/webhook/",
        views.SensorWebhookView.as_view(),
        name="sensor-webhook",
    ),
    path(
        "sensor/<int:pk>/delete/",
        views.SensorDeleteView.as_view(),
        name="sensor-delete",
    ),
]

maintenance/urls.py
from django.urls import path
from . import views

app_name = "maintenance"

urlpatterns = [
    path("task/", views.TaskFilterView.as_view(), name="task-list"),
    path(
        "task/add/",
        views.TaskCreateView.as_view(),
        name="task-create",
    ),
    path(
        "task/<int:pk>/",
        views.TaskDetailView.as_view(),
        name="task-detail",
    ),
    path(
        "task/<int:pk>/change/",
        views.TaskUpdateView.as_view(),
        name="task-update",
    ),
    path(
        "task/<int:pk>/delete/",
        views.TaskDeleteView.as_view(),
        name="task-delete",
    ),
    path("journal/", views.JournalFilterView.as_view(), name="journal-list"),
    path(
        "journal/add",
        views.JournalCreate.as_view(),
        name="journal-create",
    ),
    path(
        "journal/<int:pk>/",
        views.JournalDetailView.as_view(),
        name="journal-detail",
    ),
    path(
        "journal/<int:pk>/change/",
        views.JournalUpdateView.as_view(),
        name="journal-update",
    ),
    path(
        "journal/<int:pk>/delete/",
        views.JournalDeleteView.as_view(),
        name="journal-delete",
    ),
    path(
        "trigger/add",
        views.TriggerCreateView.as_view(),
        name="trigger-create",
    ),
    path(
        "trigger/<int:pk>/",
        views.TriggerDetailView.as_view(),
        name="trigger-detail",
    ),
    path(
        "trigger/<int:pk>/change/",
        views.TriggerUpdateView.as_view(),
        name="trigger-update",
    ),
    path(
        "trigger/<int:pk>/delete/",
        views.TriggerDeleteView.as_view(),
        name="trigger-delete",
    ),
    path(
        "document/add",
        views.DocumentCreateView.as_view(),
        name="document-create",
    ),
    path(
        "document/<int:pk>/",
        views.DocumentDetailView.as_view(),
        name="document-detail",
    ),
    path(
        "document/<int:pk>/change/",
        views.DocumentUpdateView.as_view(),
        name="document-update",
    ),
    path(
        "document/<int:pk>/delete/",
        views.DocumentDeleteView.as_view(),
        name="document-delete",
    ),
]

objector/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from django.utils.translation import gettext_lazy as _

admin.site.site_header = _("Objector admin")

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("social_django.urls")),
    path("", include("common.urls")),
    path("", include("inventory.urls")),
    path("", include("maintenance.urls")),
]

# add this lines
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

maintenance/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from rules.contrib.models import RulesModel
from inventory.models import Object, Sensor
import uuid
import pathlib
from jsonpath_ng import parse


def journal_image_upload_handler(instance, filename: str) -> str:
    file_name = str(uuid.uuid1())  # uuid1 -> uuid + timestamp
    file_suffix = pathlib.Path(filename).suffix
    return f"object/{instance.object.id}/journal/{file_name}{file_suffix}"


def document_file_upload_handler(instance, filename) -> str:
    file_name = str(uuid.uuid1())  # uuid1 -> uuid + timestamp
    file_suffix = pathlib.Path(filename).suffix
    return f"object/{instance.object.id}/document/{file_name}{file_suffix}"


class Task(RulesModel):
    class Statuses(models.IntegerChoices):
        OVERDUE = 10, _("Overdue")
        DUE = 20, _("Due")
        PENDING = 30, _("Pending")
        INACTIVE = 40, _("Inactive")

    name = models.CharField(_("Name"), max_length=200)
    description = models.TextField(_("Description"), blank=True)
    object = models.ForeignKey(
        Object,
        verbose_name=_("Object"),
        related_name="task_object",
        on_delete=models.CASCADE,
    )
    status = models.PositiveSmallIntegerField(
        _("Status"), choices=Statuses.choices, default=Statuses.PENDING
    )
    due_at = models.DateTimeField(_("Due at"), blank=True, null=True)
    overdue_at = models.DateTimeField(_("Overdue at"), blank=True, null=True)
    created_at = models.DateTimeField(_("Created at"), auto_now_add=True)
    updated_at = models.DateTimeField(_("Updated at"), auto_now=True)
    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        verbose_name=_("Created by"),
        related_name="task_created_by",
        on_delete=models.SET_NULL,
        null=True,
    )
    updated_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        verbose_name=_("Updated by"),
        related_name="task_updated_by",
        on_delete=models.SET_NULL,
        null=True,
    )

    class Meta:
        verbose_name = _("Task")
        verbose_name_plural = _("Tasks")
        ordering = ["status", "overdue_at", "due_at", "updated_at"]

    def __str__(self) -> str:
        return self.name

    def get_absolute_url(self) -> str:
        return f"/task/{self.id}"

    def get_new_task_status(self) -> int:
        now = timezone.now()
        new_task_status = Task.Statuses.PENDING
        if self.overdue_at and now >= self.overdue_at:
            new_task_status = Task.Statuses.OVERDUE
        elif self.due_at and now >= self.due_at:
            new_task_status = Task.Statuses.DUE
        return new_task_status

    @property
    def status_color(self) -> str:
        status_color = "green"
        if self.status == self.Statuses.OVERDUE:
            status_color = "red"
        elif self.status == self.Statuses.DUE:
            status_color = "amber"
        elif self.status == self.Statuses.INACTIVE:
            status_color = "grey"
        return status_color


class Journal(RulesModel):
    class Sources(models.TextChoices):
        SENSOR = "sensor", _("Sensor")
        TASK = "task", _("Task")
        OBJECT = "object", _("Object")
        LOCATION = "location", _("Location")

    object = models.ForeignKey(
        Object,
        verbose_name=_("Object"),
        related_name="journal_object",
        on_delete=models.CASCADE,
    )
    notes = models.TextField(_("Notes"), blank=True)
    image = models.ImageField(
        _("Image"), upload_to=journal_image_upload_handler, blank=True, null=True
    )
    labor_costs = models.DecimalField(
        _("Labor costs"), blank=True, null=True, decimal_places=2, max_digits=9
    )
    material_costs = models.DecimalField(
        _("Material costs"), blank=True, null=True, decimal_places=2, max_digits=9
    )
    source = models.CharField(
        _("Source"), max_length=8, choices=Sources.choices, blank=True
    )
    created_at = models.DateTimeField(_("Created at"), auto_now_add=True)
    updated_at = models.DateTimeField(_("Updated at"), auto_now=True)
    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        verbose_name=_("Created by"),
        related_name="journal_created_by",
        on_delete=models.SET_NULL,
        null=True,
    )
    updated_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        verbose_name=_("Updated by"),
        related_name="journal_updated_by",
        on_delete=models.SET_NULL,
        null=True,
    )

    def __str__(self) -> str:
        return str(self.id)

    def get_absolute_url(self) -> str:
        return f"/journal/{self.id}"

    class Meta:
        verbose_name = _("Journal")
        verbose_name_plural = _("Journals")
        ordering = ("-updated_at",)


class Trigger(RulesModel):
    class Conditions(models.TextChoices):
        EQUALS = "==", _("equals")
        NOTEQUALS = "!=", _("not equals")
        LESSTHAN = "<", _("less than")
        LESSTHANOREQUALTO = "<=", _("less than or equal to")
        GREATERTHAN = ">", _("greater than")
        GREATERTHANOREQUALTO = ">=", _("greater than or equal to")

    class Statuses(models.IntegerChoices):
        RED = 10, _("Alert")
        AMBER = 20, _("Warning")
        GREEN = 30, _("Normal")

    name = models.CharField(_("name"), max_length=200)
    sensor = models.ForeignKey(
        Sensor,
        verbose_name=_("Sensor"),
        related_name="trigger_sensor",
        on_delete=models.CASCADE,
    )
    jsonpath_expression = models.CharField(
        _("JSONPath expression"),
        max_length=200,
        help_text='Use <a href="http://json2jsonpath.com" target="_blank">JSONPath generator</a>'
        " with expected JSON payload.",
    )
    condition = models.CharField(
        _("Condition"), max_length=2, choices=Conditions.choices
    )
    sensor_value = models.CharField(_("Sensor value"), max_length=200, blank=True)
    amber_value = models.CharField(_("Warning value"), max_length=200, blank=True)
    red_value = models.CharField(_("Alert value"), max_length=200, blank=True)
    status = models.PositiveSmallIntegerField(
        _("Status"), choices=Statuses.choices, default=Statuses.GREEN
    )
    created_at = models.DateTimeField(_("Created at"), auto_now_add=True)
    updated_at = models.DateTimeField(_("Updated at"), auto_now=True)
    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        verbose_name=_("Created by"),
        related_name="trigger_created_by",
        on_delete=models.SET_NULL,
        null=True,
    )
    updated_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        verbose_name=_("Updated by"),
        related_name="trigger_updated_by",
        on_delete=models.SET_NULL,
        null=True,
    )

    def __str__(self) -> str:
        return self.name

    def get_absolute_url(self) -> str:
        return f"/trigger/{self.id}"

    @property
    def status_color(self) -> str:
        status_color = "green"
        if self.status == Trigger.Statuses.RED:
            status_color = "red"
        elif self.status == Trigger.Statuses.AMBER:
            status_color = "amber"
        return status_color

    def get_trigger_sensor_value(
        self, match_value, trigger_condition: str, trigger_value: str
    ) -> str:
        trigger_sensor_value = ""
        type_matched_trigger_value = match_value

        if match_value and trigger_condition and trigger_value:
            try:
                type_matched_trigger_value = type(match_value)(trigger_value)
            except ValueError:
                trigger_sensor_value = "Error: Type mismatch. Matched value can't be compared to trigger value."

            if len(str(match_value)) > 200:
                trigger_sensor_value = (
                    "Error: Sensor value to long. Check JSONPath expression."
                )
            elif (
                (
                    Trigger.Conditions.EQUALS == trigger_condition
                    and match_value == type_matched_trigger_value
                )
                or (
                    Trigger.Conditions.NOTEQUALS == trigger_condition
                    and match_value != type_matched_trigger_value
                )
                or (
                    Trigger.Conditions.LESSTHAN == trigger_condition
                    and match_value < type_matched_trigger_value
                )
                or (
                    Trigger.Conditions.LESSTHANOREQUALTO == trigger_condition
                    and match_value <= type_matched_trigger_value
                )
                or (
                    Trigger.Conditions.GREATERTHAN == trigger_condition
                    and match_value > type_matched_trigger_value
                )
                or (
                    Trigger.Conditions.GREATERTHANOREQUALTO == trigger_condition
                    and match_value >= type_matched_trigger_value
                )
            ):
                trigger_sensor_value = str(match_value)

        return trigger_sensor_value

    def set_trigger_status_and_sensor_value(self, object_webhook_payload: str) -> None:
        trigger_status = self.Statuses.GREEN
        trigger_sensor_value = ""
        jsonpath_expression = parse(self.jsonpath_expression)

        for match in jsonpath_expression.find(object_webhook_payload):
            if trigger_status > self.Statuses.RED:
                trigger_sensor_value_red = ""
                trigger_sensor_value_red = self.get_trigger_sensor_value(
                    match.value,
                    self.condition,
                    self.red_value,
                )
                if trigger_sensor_value_red:
                    trigger_status = self.Statuses.RED
                    trigger_sensor_value = trigger_sensor_value_red

            if trigger_status > self.Statuses.AMBER:

maintenance/templates/maintenance/journal_detail.html
{% extends "base.html" %}
{% load i18n %}
{% load rules %}
{% block title %}Objector + {% translate "Journal detail" %} + {{ journal }}{% endblock %}
{% block h1 %}{% translate "Journal detail" %}{% endblock %}
{% block h2 %}{{ journal }}{% endblock %}
{% block content %}
<section aria-labelledby="journal-detail-title">
  <div class="bg-white shadow sm:rounded-lg">
    <div class="px-4 py-5 sm:px-6">
      <h2 id="journal-detail-title" class="text-lg leading-6 font-medium text-gray-900">
        {% translate "Journal detail" %}
      </h2>
    </div>
    <div class="border-t border-gray-200 px-4 py-5 sm:px-6">
      <dl class="grid grid-cols-1 gap-x-4 gap-y-8 sm:grid-cols-2">
        <div class="sm:col-span-2">
          <dt class="text-sm font-medium text-gray-500">
            {% translate "Object" %}
          </dt>
          <dd class="mt-1 text-sm text-gray-900">
            {% if journal.object %}
            <a href="{% url 'inventory:object-detail' journal.object.id %}">
              {{ journal.object }}
            </a>
            {% else %}
            {{ journal.object }}
            {% endif %}
          </dd>
        </div>
        <div class="sm:col-span-2">
          <dt class="text-sm font-medium text-gray-500">
            {% translate "Notes" %}
          </dt>
          <dd class="mt-1 text-sm text-gray-900">
            {{ journal.notes|linebreaksbr }}
          </dd>
        </div>
        <div class="sm:col-span-2">
          <dt class="text-sm font-medium text-gray-500">
            {% translate "Image" %}
          </dt>
          <dd class="mt-1 text-sm text-gray-900">
            {% if journal.image %}
            <a href="{{ journal.image.url }}" target="_blank">
              <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
                <path stroke-linecap="round" stroke-linejoin="round" d="M4 16l4.586-4.586a2 2 0 012.828 0L16 16m-2-2l1.586-1.586a2 2 0 012.828 0L20 14m-6-6h.01M6 20h12a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v12a2 2 0 002 2z" />
              </svg>
            </a>
            {% endif %}
          </dd>
        </div>
      </dl>
    </div>
    <div class="border-t border-gray-200 px-4 py-5 sm:px-6">
      <dl class="grid grid-cols-1 gap-x-4 gap-y-8 sm:grid-cols-2">
        <div class="sm:col-span-1">
          <dt class="text-sm font-medium text-gray-500">
            {% translate "Labor costs" %}
          </dt>
          <dd class="mt-1 text-sm text-gray-900">
            {{ journal.labor_costs }}
          </dd>
        </div>
        <div class="sm:col-span-1">
          <dt class="text-sm font-medium text-gray-500">
            {% translate "Material costs" %}
          </dt>
          <dd class="mt-1 text-sm text-gray-900">
            {{ journal.material_costs }}
          </dd>
        </div>
      </dl>
    </div>
    <div class="border-t border-gray-200 px-4 py-5 sm:px-6">
      <dl class="grid grid-cols-1 gap-x-4 gap-y-8 sm:grid-cols-2">
        <div class="sm:col-span-1">
          <dt class="text-sm font-medium text-gray-500">
            {% translate "Created at" %}
          </dt>
          <dd class="mt-1 text-sm text-gray-900">
            {{ journal.created_at }}
          </dd>
        </div>
        <div class="sm:col-span-1">
          <dt class="text-sm font-medium text-gray-500">
            {% translate "Updated at" %}
          </dt>
          <dd class="mt-1 text-sm text-gray-900">
            {{ journal.updated_at }}
          </dd>
        </div>
        <div class="sm:col-span-1">
          <dt class="text-sm font-medium text-gray-500">
            {% translate "Created by" %}
          </dt>
          <dd class="mt-1 text-sm text-gray-900">
            {{ journal.created_by }}
          </dd>
        </div>
        <div class="sm:col-span-1">
          <dt class="text-sm font-medium text-gray-500">
            {% translate "Updated by" %}
          </dt>
          <dd class="mt-1 text-sm text-gray-900">
            {{ journal.updated_by }}
          </dd>
        </div>
      </dl>
    </div>
    <div class="border-t border-gray-200 px-4 py-5 sm:px-6">
      <div class="pt-5">
        <div class="flex justify-end">
          {% has_perm 'maintenance.change_journal' user journal as can_change_journal %}
          {% if can_change_journal %}
          <a href="{% url 'maintenance:journal-update' journal.id %}" class="ml-3 inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
            {% translate "Change" %}
          </a>
          {% endif %}
          <a href="{% url 'maintenance:journal-list' %}" class="ml-3 bg-white py-2 px-4 border border-gray-300 rounded-md shadow-sm text-sm font-medium text-gray-700 hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
            {% translate "List" %}
          </a>
          {% has_perm 'maintenance.delete_journal' user journal as can_delete_journal %}
          {% if can_delete_journal %}
          <a href="{% url 'maintenance:journal-delete' journal.id %}" class="ml-3 bg-white py-2 px-4 border border-gray-300 rounded-md shadow-sm text-sm font-medium text-gray-700 hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
            {% translate "Delete" %}
          </a>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}

maintenance/templates/maintenance/journal_filter.html
{% extends "base.html" %}
{% load i18n %}
{% load humanize %}
{% load rules %}
{% load crispy_forms_tags %}
{% block title %}Objector + {% translate "Journal list" %}{% endblock %}
{% block h1 %}{% translate "Journal list" %}{% endblock %}
{% block content %}
<div class="pb-5 border-b border-gray-200">
  <h3 class="text-lg leading-6 font-medium text-gray-900">Filter</h3>
</div>
<form method="get">
  {{ filter.form | crispy }}
  <div class="pt-5">
    <div class="flex justify-end">
        <button type="submit" class="bg-white py-2 px-4 border border-gray-300 rounded-md shadow-sm text-sm font-medium text-gray-700 hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
            {% translate "Apply filter" %}
        </button>
    </div>
</div>
</form>
<div class="pb-5 border-b border-gray-200">
  <h3 class="text-lg leading-6 font-medium text-gray-900">{% translate "List" %}</h3>
</div>
{% if journal_list %}
<div class="flex flex-col">
  <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
    <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
      <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
        <table class="min-w-full divide-y divide-gray-200">
          <thead class="bg-gray-50">
            <tr>
              <th scope="col" class="whitespace-nowrap py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-6">
                {% translate "ID" %}
              </th>
              <th scope="col" class="whitespace-nowrap px-2 py-3.5 text-left text-sm font-semibold text-gray-900">
                {% translate "Object" %}
              </th>
              <th scope="col" class="whitespace-nowrap px-2 py-3.5 text-left text-sm font-semibold text-gray-900">
                {% translate "Notes" %}
              </th>
              <th scope="col" class="whitespace-nowrap px-2 py-3.5 text-left text-sm font-semibold text-gray-900">
                {% translate "Image" %}
              </th>
              <th scope="col" class="whitespace-nowrap px-2 py-3.5 text-left text-sm font-semibold text-gray-900 hidden md:table-cell">
                {% translate "Labor costs" %}
              </th>
              <th scope="col" class="whitespace-nowrap px-2 py-3.5 text-left text-sm font-semibold text-gray-900 hidden md:table-cell">
                {% translate "Material costs" %}
              </th>
              <th scope="col" class="relative whitespace-nowrap py-3.5 pl-3 pr-4 sm:pr-6 hidden lg:table-cell">
                <span class="sr-only">{% translate "Action" %}</span>
              </th>
            </tr>
          </thead>
          <tbody>
            {% for journal in journal_list %}
            <tr class="bg-white">
              <td class="whitespace-nowrap py-2 pl-4 pr-3 text-sm text-gray-500 sm:pl-6">
                <div class="inline-flex items-baseline px-2.5 py-0.5 rounded-full bg-gray-100 text-gray-800">
                <a href="{% url 'maintenance:journal-detail' journal.id %}">{{ journal.id }}</a>
              </div>
              </td>
              <td class="whitespace-nowrap px-2 py-2 text-sm font-medium text-gray-900">
                <a href="{% url 'inventory:object-detail' journal.object.id %}">
                  {{ journal.object }}
                </a>
              </td>
              <td class="whitespace-nowrap px-2 py-2 text-sm text-gray-500">
                {{ journal.notes|truncatechars:20 }}
              </td>
              <td class="whitespace-nowrap px-2 py-2 text-sm text-gray-500">
                {% if journal.image %}
                <a href="{{ journal.image.url }}" target="_blank">
                  <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M4 16l4.586-4.586a2 2 0 012.828 0L16 16m-2-2l1.586-1.586a2 2 0 012.828 0L20 14m-6-6h.01M6 20h12a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v12a2 2 0 002 2z" />
                  </svg>
                </a>
                {% endif %}
              </td>
              <td class="whitespace-nowrap px-2 py-2 text-sm text-gray-500 hidden md:table-cell">
                {{ journal.labor_costs }}
              </td>
              <td class="whitespace-nowrap px-2 py-2 text-sm text-gray-500 hidden md:table-cell">
                {{ journal.material_costs }}
              </td>
              <td class="relative whitespace-nowrap py-2 pl-3 pr-4 text-right text-sm font-medium sm:pr-6 hidden lg:table-cell">
                <div class="ml-4 flex-shrink-0 flex space-x-4 justify-end">
                  {% has_perm 'journal.view_journal' user journal as can_view_journal %}
                  {% if can_view_journal %}
                  <a href="{% url 'maintenance:journal-detail' journal.id %}" class="text-indigo-600 hover:text-indigo-900">
                    {% translate "View" %}
                  </a>
                  {% endif %}
                  {% has_perm 'journal.change_journal' user journal as can_change_journal %}
                  {% if can_change_journal %}
                  <a href="{% url 'maintenance:journal-update' journal.id %}" class="text-indigo-600 hover:text-indigo-900">
                    {% translate "Change" %}
                  </a>
                  {% endif %}
                  {% has_perm 'journal.delete_journal' user journal as can_delete_journal %}
                  {% if can_delete_journal %}
                  <a href="{% url 'maintenance:journal-delete' journal.id %}" class="text-indigo-600 hover:text-indigo-900">
                    {% translate "Delete" %}
                  </a>
                  {% endif %}
                </div>
              </td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
        <nav class="bg-white px-4 py-3 flex items-center justify-between border-t border-gray-200 sm:px-6"
          aria-label="Pagination">
          <div class="hidden sm:block">
            <p class="text-sm text-gray-700">
              {% translate "Showing page" %}
              <span class="font-medium">{{ page_obj.number }}</span>
              {% translate "of" %}
              <span class="font-medium">{{ page_obj.paginator.num_pages }}</span>
            </p>
          </div>
          <div class="flex-1 flex justify-between sm:justify-end">
            {% if page_obj.has_previous %}
            <a href="?page={{ page_obj.previous_page_number }}"
              class="relative inline-flex items-center px-4 py-2 border border-gray-300 text-sm font-medium rounded-md text-gray-700 bg-white hover:bg-gray-50">
              {% translate "Previous" %}
            </a>
            {% endif %}
            {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}"
              class="ml-3 relative inline-flex items-center px-4 py-2 border border-gray-300 text-sm font-medium rounded-md text-gray-700 bg-white hover:bg-gray-50">
              {% translate "Next" %}
            </a>
            {% endif %}
          </div>
        </nav>
      </div>
    </div>
  </div>
</div>
{% endif %}
{% has_perm 'maintenance.add_journal' user journal as can_add_journal %}
{% if can_add_journal %}
<div class="px-4 py-3 bg-gray-50 text-right sm:px-6">
  <a href="{% url 'maintenance:journal-create' %}" class="inline-flex items-center p-2 border border-transparent rounded-full shadow-sm text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
    <!-- Heroicon name: outline/plus-sm -->
    <svg class="h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 6v6m0 0v6m0-6h6m-6 0H6" />
    </svg>
  </a>
</div>
{% endif %}
{% endblock %}